### PR TITLE
Add name and icon

### PR DESCRIPTION
**Pull request by hfm**
Implements options of `-icon` and `-name`: https://github.com/kentaro/takosan#options

### CODE REVIEW

**Comment by hfm** [comment]
@hsbt Please review this PR? :cat:

**Comment by hsbt** [comment]
:octocat: That's ok.

**Comment by hfm** [comment]
Thanks! :octopus:

**Comment by hfm** [comment]
released https://rubygems.org/gems/takosan/versions/1.1.0

**Pull request merged**
